
from llm.llm import extract_car_markdown, rewrite_query, send_user_message
from dotenv import load_dotenv
import os


load_dotenv()

def user_request(input:str) -> str:
    """
        Processes a user input to retrieve car-related information.

        The function rewrites the input into an optimized query, sends it to the LLM,
        and returns the generated response.

        Args:
            input (str): Raw user input received from the API.

        Returns:
            str: The response generated by the LLM based on the processed query.

        Raises:
            ValueError: If the input is empty or if the response is empty.
    """

    if len(input) == 0:
        raise ValueError("Input is Empty")

    
    re_query = rewrite_query(input)

   
    response = send_user_message(input, query_rewrite=re_query)

    if not response:
        raise ValueError("RESPONSE EMPTY")
    

    return response

        

